sources:
  - ./TestingTask/Core/Services/Data/AuthService/AuthService.swift
  - ./TestingTask/Core/Services/Data/NewsService/INewsService.swift
  - ./TestingTask/Core/Services/Data/Storage/IStorageService.swift
  - ./TestingTask/Core/Services/Data/Cache/ICacheService.swift
  - ./TestingTask/Core/Services/Presentation/ErrorService/IErrorService.swift
  - ./TestingTask/Core/Services/Presentation/ProgressService/IProgressService.swift
  - ./TestingTask/Core/Sources/LoginScreen/View/LoginScreenViewInput.swift
  - ./TestingTask/Core/Sources/LoginScreen/Router/LoginScreenRouterInput.swift
  - ./TestingTask/Core/Sources/SignUpScreen/View/SignUpScreenViewInput.swift
  - ./TestingTask/Core/Sources/SignUpScreen/Router/SignUpScreenRouterInput.swift
  - ./TestingTask/Core/Sources/NewsScreen/View/NewsViewInput.swift
  - ./TestingTask/Core/Sources/NewsScreen/Router/NewsRouterInput.swift
  - ./TestingTask/Core/Sources/ArticleScreen/View/ArticleViewInput.swift
  - ./TestingTask/Core/Sources/ArticleScreen/Router/ArticleRouterInput.swift
  - ./TestingTask/Core/Sources/FavoriteScreen/View/FavoriteViewInput.swift
  - ./TestingTask/Core/Sources/FavoriteScreen/Router/FavoriteRouterInput.swift
templates:
  - ./Mock.swifttemplate
output: ./TestingTaskTests/Mocks/GeneratedMocks.swift
args:
  testable:
    - TestingTask
  import:
    - UIKit
    - Foundation
